SOURCES += \
    ./Localization/Slam/SensorTimer/Edit/SensorTimer_Localization_Slam_PrivFunc.cpp \
    ./Localization/Slam/SensorTimer/NoEdit/SensorTimer_Localization_Slam_PrivCoreFunc.cpp \
    ./Localization/Slam/Simulator/Edit/Simulator_Localization_Slam_PrivFunc.cpp \
    ./Localization/Slam/Simulator/NoEdit/Simulator_Localization_Slam_PrivCoreFunc.cpp \
    ./Processor/Control/ProcessorMulti/Edit/ProcessorMulti_Processor_Control_PrivFunc.cpp \
    ./Processor/Control/ProcessorMulti/NoEdit/ProcessorMulti_Processor_Control_PrivCoreFunc.cpp \
    ./Processor/Control/control.cpp \
    ./Processor/EvaluateFunction/ProcessorMono/Edit/learning.cpp \
    ./Processor/EvaluateFunction/ProcessorMono/Edit/ProcessorMono_Processor_EvaluateFunction_PrivFunc.cpp \
    ./Processor/EvaluateFunction/ProcessorMono/NoEdit/ProcessorMono_Processor_EvaluateFunction_PrivCoreFunc.cpp \
    ./Processor/FeatureExtract/ProcessorMulti/Edit/ProcessorMulti_Processor_FeatureExtract_PrivFunc.cpp \
    ./Processor/FeatureExtract/ProcessorMulti/NoEdit/ProcessorMulti_Processor_FeatureExtract_PrivCoreFunc.cpp \
    ./Processor/FeatureExtract/ProcessorMulti/processormulti_processor_featureextract_ex.cpp \
    ./Processor/FeatureExtract/VisualizationMono/Edit/VisualizationMono_Processor_FeatureExtract_PrivFunc.cpp \
    ./Processor/FeatureExtract/VisualizationMono/NoEdit/VisualizationMono_Processor_FeatureExtract_PrivCoreFunc.cpp \
    ./Processor/PathGenerator/ProcessorMulti/Edit/ProcessorMulti_Processor_PathGenerator_PrivFunc.cpp \
    ./Processor/PathGenerator/ProcessorMulti/NoEdit/ProcessorMulti_Processor_PathGenerator_PrivCoreFunc.cpp \
    ./Processor/PathGenerator/VisualizationMono/Edit/controlvis.cpp \
    ./Processor/PathGenerator/VisualizationMono/Edit/VisualizationMono_Processor_PathGenerator_PrivFunc.cpp \
    ./Processor/PathGenerator/VisualizationMono/NoEdit/VisualizationMono_Processor_PathGenerator_PrivCoreFunc.cpp \
    ./Sensor/Camera/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Camera_PrivFunc.cpp \
    ./Sensor/Camera/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Camera_PrivCoreFunc.cpp \
    ./Sensor/Camera/Simulator/Edit/Simulator_Sensor_Camera_PrivFunc.cpp \
    ./Sensor/Camera/Simulator/NoEdit/Simulator_Sensor_Camera_PrivCoreFunc.cpp \
    ./Sensor/Camera/StorageMono/Edit/StorageMono_Sensor_Camera_PrivFunc.cpp \
    ./Sensor/Camera/StorageMono/NoEdit/StorageMono_Sensor_Camera_PrivCoreFunc.cpp \
    ./Sensor/Camera/VisualizationMono/Edit/VisualizationMono_Sensor_Camera_PrivFunc.cpp \
    ./Sensor/Camera/VisualizationMono/NoEdit/VisualizationMono_Sensor_Camera_PrivCoreFunc.cpp \
    ./Sensor/Joystick/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Joystick_PrivFunc.cpp \
    ./Sensor/Joystick/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Joystick_PrivCoreFunc.cpp \
    ./Sensor/Joystick/StorageMono/Edit/StorageMono_Sensor_Joystick_PrivFunc.cpp \
    ./Sensor/Joystick/StorageMono/NoEdit/StorageMono_Sensor_Joystick_PrivCoreFunc.cpp \
    ./Sensor/Joystick/VisualizationMono/Edit/VisualizationMono_Sensor_Joystick_PrivFunc.cpp \
    ./Sensor/Joystick/VisualizationMono/NoEdit/VisualizationMono_Sensor_Joystick_PrivCoreFunc.cpp \
    ./Sensor/Laser/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Laser_PrivFunc.cpp \
    ./Sensor/Laser/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Laser_PrivCoreFunc.cpp \
    ./Sensor/Laser/Simulator/Edit/Simulator_Sensor_Laser_PrivFunc.cpp \
    ./Sensor/Laser/Simulator/NoEdit/Simulator_Sensor_Laser_PrivCoreFunc.cpp \
    ./Sensor/Laser/StorageMono/Edit/StorageMono_Sensor_Laser_PrivFunc.cpp \
    ./Sensor/Laser/StorageMono/NoEdit/StorageMono_Sensor_Laser_PrivCoreFunc.cpp \
    ./Sensor/Laser/VisualizationMono/Edit/VisualizationMono_Sensor_Laser_PrivFunc.cpp \
    ./Sensor/Laser/VisualizationMono/NoEdit/VisualizationMono_Sensor_Laser_PrivCoreFunc.cpp \
    ./Sensor/stm32comm/Simulator/Edit/Simulator_Sensor_stm32comm_PrivFunc.cpp \
    ./Sensor/stm32comm/Simulator/NoEdit/Simulator_Sensor_stm32comm_PrivCoreFunc.cpp \
    ./Sensor/stm32comm/SourceDrainMono/Edit/SourceDrainMono_Sensor_stm32comm_PrivFunc.cpp \
    ./Sensor/stm32comm/SourceDrainMono/NoEdit/SourceDrainMono_Sensor_stm32comm_PrivCoreFunc.cpp \
    ./Sensor/stm32comm/StorageMono/Edit/StorageMono_Sensor_stm32comm_PrivFunc.cpp \
    ./Sensor/stm32comm/StorageMono/NoEdit/StorageMono_Sensor_stm32comm_PrivCoreFunc.cpp \
    ./Sensor/stm32comm/VisualizationMono/Edit/VisualizationMono_Sensor_stm32comm_PrivFunc.cpp \
    ./Sensor/stm32comm/VisualizationMono/NoEdit/VisualizationMono_Sensor_stm32comm_PrivCoreFunc.cpp \
    ./VisualMisc/ControlJoy/VisualizationMulti/Edit/VisualizationMulti_VisualMisc_ControlJoy_PrivFunc.cpp \
    ./VisualMisc/ControlJoy/VisualizationMulti/NoEdit/VisualizationMulti_VisualMisc_ControlJoy_PrivCoreFunc.cpp\
	./VisualMisc/CombinedVisual/VisualizationMulti/Edit/VisualizationMulti_VisualMisc_CombinedVisual_PrivFunc.cpp	\
        ./VisualMisc/CombinedVisual/VisualizationMulti/NoEdit/VisualizationMulti_VisualMisc_CombinedVisual_PrivCoreFunc.cpp\
	./Processor/PathGenerator/Simulator/Edit/Simulator_Processor_PathGenerator_PrivFunc.cpp	\
        ./Processor/PathGenerator/Simulator/NoEdit/Simulator_Processor_PathGenerator_PrivCoreFunc.cpp \
    $$PWD/Processor/PathGenerator/ProcessorMulti/barrier_detect.cpp \
    $$PWD/VisualMisc/CombinedVisual/VisualizationMulti/sensorwidgets.cpp

HEADERS += \
    ./Localization/Slam/SensorTimer/Edit/SensorTimer_Localization_Slam_ParamsData.h \
    ./Localization/Slam/SensorTimer/Edit/SensorTimer_Localization_Slam_Vars.h \
    ./Localization/Slam/SensorTimer/NoEdit/SensorTimer_Localization_Slam_PrivCoreFunc.h \
    ./Localization/Slam/SensorTimer/NoEdit/SensorTimer_Localization_Slam_PrivFunc.h \
    ./Localization/Slam/Simulator/Edit/Simulator_Localization_Slam_ParamsData.h \
    ./Localization/Slam/Simulator/Edit/Simulator_Localization_Slam_Vars.h \
    ./Localization/Slam/Simulator/NoEdit/Simulator_Localization_Slam_PrivCoreFunc.h \
    ./Localization/Slam/Simulator/NoEdit/Simulator_Localization_Slam_PrivFunc.h \
    ./Processor/Control/ProcessorMulti/Edit/ProcessorMulti_Processor_Control_ParamsData.h \
    ./Processor/Control/ProcessorMulti/Edit/ProcessorMulti_Processor_Control_Vars.h \
    ./Processor/Control/ProcessorMulti/NoEdit/ProcessorMulti_Processor_Control_PrivCoreFunc.h \
    ./Processor/Control/ProcessorMulti/NoEdit/ProcessorMulti_Processor_Control_PrivFunc.h \
    ./Processor/Control/control.h \
    ./Processor/EvaluateFunction/ProcessorMono/Edit/learning.h \
    ./Processor/EvaluateFunction/ProcessorMono/Edit/ProcessorMono_Processor_EvaluateFunction_ParamsData.h \
    ./Processor/EvaluateFunction/ProcessorMono/Edit/ProcessorMono_Processor_EvaluateFunction_Vars.h \
    ./Processor/EvaluateFunction/ProcessorMono/NoEdit/ProcessorMono_Processor_EvaluateFunction_PrivCoreFunc.h \
    ./Processor/EvaluateFunction/ProcessorMono/NoEdit/ProcessorMono_Processor_EvaluateFunction_PrivFunc.h \
    ./Processor/FeatureExtract/ProcessorMulti/Edit/ProcessorMulti_Processor_FeatureExtract_ParamsData.h \
    ./Processor/FeatureExtract/ProcessorMulti/Edit/ProcessorMulti_Processor_FeatureExtract_Vars.h \
    ./Processor/FeatureExtract/ProcessorMulti/NoEdit/ProcessorMulti_Processor_FeatureExtract_PrivCoreFunc.h \
    ./Processor/FeatureExtract/ProcessorMulti/NoEdit/ProcessorMulti_Processor_FeatureExtract_PrivFunc.h \
    ./Processor/FeatureExtract/ProcessorMulti/processormulti_processor_featureextract_ex.h \
    ./Processor/FeatureExtract/VisualizationMono/Edit/VisualizationMono_Processor_FeatureExtract_ParamsData.h \
    ./Processor/FeatureExtract/VisualizationMono/Edit/VisualizationMono_Processor_FeatureExtract_Vars.h \
    ./Processor/FeatureExtract/VisualizationMono/NoEdit/VisualizationMono_Processor_FeatureExtract_PrivCoreFunc.h \
    ./Processor/FeatureExtract/VisualizationMono/NoEdit/VisualizationMono_Processor_FeatureExtract_PrivFunc.h \
    ./Processor/PathGenerator/ProcessorMulti/Edit/ProcessorMulti_Processor_PathGenerator_ParamsData.h \
    ./Processor/PathGenerator/ProcessorMulti/Edit/ProcessorMulti_Processor_PathGenerator_Vars.h \
    ./Processor/PathGenerator/ProcessorMulti/NoEdit/ProcessorMulti_Processor_PathGenerator_PrivCoreFunc.h \
    ./Processor/PathGenerator/ProcessorMulti/NoEdit/ProcessorMulti_Processor_PathGenerator_PrivFunc.h \
    ./Processor/PathGenerator/VisualizationMono/Edit/controlvis.h \
    ./Processor/PathGenerator/VisualizationMono/Edit/VisualizationMono_Processor_PathGenerator_ParamsData.h \
    ./Processor/PathGenerator/VisualizationMono/Edit/VisualizationMono_Processor_PathGenerator_Vars.h \
    ./Processor/PathGenerator/VisualizationMono/NoEdit/VisualizationMono_Processor_PathGenerator_PrivCoreFunc.h \
    ./Processor/PathGenerator/VisualizationMono/NoEdit/VisualizationMono_Processor_PathGenerator_PrivFunc.h \
    ./Sensor/Camera/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Camera_ParamsData.h \
    ./Sensor/Camera/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Camera_Vars.h \
    ./Sensor/Camera/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Camera_PrivCoreFunc.h \
    ./Sensor/Camera/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Camera_PrivFunc.h \
    ./Sensor/Camera/Simulator/Edit/Simulator_Sensor_Camera_ParamsData.h \
    ./Sensor/Camera/Simulator/Edit/Simulator_Sensor_Camera_Vars.h \
    ./Sensor/Camera/Simulator/NoEdit/Simulator_Sensor_Camera_PrivCoreFunc.h \
    ./Sensor/Camera/Simulator/NoEdit/Simulator_Sensor_Camera_PrivFunc.h \
    ./Sensor/Camera/StorageMono/Edit/StorageMono_Sensor_Camera_ParamsData.h \
    ./Sensor/Camera/StorageMono/Edit/StorageMono_Sensor_Camera_Vars.h \
    ./Sensor/Camera/StorageMono/NoEdit/StorageMono_Sensor_Camera_PrivCoreFunc.h \
    ./Sensor/Camera/StorageMono/NoEdit/StorageMono_Sensor_Camera_PrivFunc.h \
    ./Sensor/Camera/VisualizationMono/Edit/VisualizationMono_Sensor_Camera_ParamsData.h \
    ./Sensor/Camera/VisualizationMono/Edit/VisualizationMono_Sensor_Camera_Vars.h \
    ./Sensor/Camera/VisualizationMono/NoEdit/VisualizationMono_Sensor_Camera_PrivCoreFunc.h \
    ./Sensor/Camera/VisualizationMono/NoEdit/VisualizationMono_Sensor_Camera_PrivFunc.h \
    ./Sensor/Joystick/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Joystick_ParamsData.h \
    ./Sensor/Joystick/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Joystick_Vars.h \
    ./Sensor/Joystick/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Joystick_PrivCoreFunc.h \
    ./Sensor/Joystick/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Joystick_PrivFunc.h \
    ./Sensor/Joystick/StorageMono/Edit/StorageMono_Sensor_Joystick_ParamsData.h \
    ./Sensor/Joystick/StorageMono/Edit/StorageMono_Sensor_Joystick_Vars.h \
    ./Sensor/Joystick/StorageMono/NoEdit/StorageMono_Sensor_Joystick_PrivCoreFunc.h \
    ./Sensor/Joystick/StorageMono/NoEdit/StorageMono_Sensor_Joystick_PrivFunc.h \
    ./Sensor/Joystick/VisualizationMono/Edit/VisualizationMono_Sensor_Joystick_ParamsData.h \
    ./Sensor/Joystick/VisualizationMono/Edit/VisualizationMono_Sensor_Joystick_Vars.h \
    ./Sensor/Joystick/VisualizationMono/NoEdit/VisualizationMono_Sensor_Joystick_PrivCoreFunc.h \
    ./Sensor/Joystick/VisualizationMono/NoEdit/VisualizationMono_Sensor_Joystick_PrivFunc.h \
    ./Sensor/Laser/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Laser_ParamsData.h \
    ./Sensor/Laser/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Laser_Vars.h \
    ./Sensor/Laser/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Laser_PrivCoreFunc.h \
    ./Sensor/Laser/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Laser_PrivFunc.h \
    ./Sensor/Laser/Simulator/Edit/Simulator_Sensor_Laser_ParamsData.h \
    ./Sensor/Laser/Simulator/Edit/Simulator_Sensor_Laser_Vars.h \
    ./Sensor/Laser/Simulator/NoEdit/Simulator_Sensor_Laser_PrivCoreFunc.h \
    ./Sensor/Laser/Simulator/NoEdit/Simulator_Sensor_Laser_PrivFunc.h \
    ./Sensor/Laser/StorageMono/Edit/StorageMono_Sensor_Laser_ParamsData.h \
    ./Sensor/Laser/StorageMono/Edit/StorageMono_Sensor_Laser_Vars.h \
    ./Sensor/Laser/StorageMono/NoEdit/StorageMono_Sensor_Laser_PrivCoreFunc.h \
    ./Sensor/Laser/StorageMono/NoEdit/StorageMono_Sensor_Laser_PrivFunc.h \
    ./Sensor/Laser/VisualizationMono/Edit/VisualizationMono_Sensor_Laser_ParamsData.h \
    ./Sensor/Laser/VisualizationMono/Edit/VisualizationMono_Sensor_Laser_Vars.h \
    ./Sensor/Laser/VisualizationMono/NoEdit/VisualizationMono_Sensor_Laser_PrivCoreFunc.h \
    ./Sensor/Laser/VisualizationMono/NoEdit/VisualizationMono_Sensor_Laser_PrivFunc.h \
    ./Sensor/stm32comm/Simulator/Edit/Simulator_Sensor_stm32comm_ParamsData.h \
    ./Sensor/stm32comm/Simulator/Edit/Simulator_Sensor_stm32comm_Vars.h \
    ./Sensor/stm32comm/Simulator/NoEdit/Simulator_Sensor_stm32comm_PrivCoreFunc.h \
    ./Sensor/stm32comm/Simulator/NoEdit/Simulator_Sensor_stm32comm_PrivFunc.h \
    ./Sensor/stm32comm/SourceDrainMono/Edit/SourceDrainMono_Sensor_stm32comm_ParamsData.h \
    ./Sensor/stm32comm/SourceDrainMono/Edit/SourceDrainMono_Sensor_stm32comm_Vars.h \
    ./Sensor/stm32comm/SourceDrainMono/NoEdit/SourceDrainMono_Sensor_stm32comm_PrivCoreFunc.h \
    ./Sensor/stm32comm/SourceDrainMono/NoEdit/SourceDrainMono_Sensor_stm32comm_PrivFunc.h \
    ./Sensor/stm32comm/StorageMono/Edit/StorageMono_Sensor_stm32comm_ParamsData.h \
    ./Sensor/stm32comm/StorageMono/Edit/StorageMono_Sensor_stm32comm_Vars.h \
    ./Sensor/stm32comm/StorageMono/NoEdit/StorageMono_Sensor_stm32comm_PrivCoreFunc.h \
    ./Sensor/stm32comm/StorageMono/NoEdit/StorageMono_Sensor_stm32comm_PrivFunc.h \
    ./Sensor/stm32comm/VisualizationMono/Edit/VisualizationMono_Sensor_stm32comm_ParamsData.h \
    ./Sensor/stm32comm/VisualizationMono/Edit/VisualizationMono_Sensor_stm32comm_Vars.h \
    ./Sensor/stm32comm/VisualizationMono/NoEdit/VisualizationMono_Sensor_stm32comm_PrivCoreFunc.h \
    ./Sensor/stm32comm/VisualizationMono/NoEdit/VisualizationMono_Sensor_stm32comm_PrivFunc.h \
    ./VisualMisc/ControlJoy/VisualizationMulti/Edit/VisualizationMulti_VisualMisc_ControlJoy_ParamsData.h \
    ./VisualMisc/ControlJoy/VisualizationMulti/Edit/VisualizationMulti_VisualMisc_ControlJoy_Vars.h \
    ./VisualMisc/ControlJoy/VisualizationMulti/NoEdit/VisualizationMulti_VisualMisc_ControlJoy_PrivCoreFunc.h \
    ./VisualMisc/ControlJoy/VisualizationMulti/NoEdit/VisualizationMulti_VisualMisc_ControlJoy_PrivFunc.h\
	./VisualMisc/CombinedVisual/VisualizationMulti/Edit/VisualizationMulti_VisualMisc_CombinedVisual_ParamsData.h	\
	./VisualMisc/CombinedVisual/VisualizationMulti/Edit/VisualizationMulti_VisualMisc_CombinedVisual_Vars.h	\
	./VisualMisc/CombinedVisual/VisualizationMulti/NoEdit/VisualizationMulti_VisualMisc_CombinedVisual_PrivFunc.h	\
        ./VisualMisc/CombinedVisual/VisualizationMulti/NoEdit/VisualizationMulti_VisualMisc_CombinedVisual_PrivCoreFunc.h\
	./Processor/PathGenerator/Simulator/Edit/Simulator_Processor_PathGenerator_ParamsData.h	\
	./Processor/PathGenerator/Simulator/Edit/Simulator_Processor_PathGenerator_Vars.h	\
	./Processor/PathGenerator/Simulator/NoEdit/Simulator_Processor_PathGenerator_PrivFunc.h	\
	./Processor/PathGenerator/Simulator/NoEdit/Simulator_Processor_PathGenerator_PrivCoreFunc.h \	
    $$PWD/Processor/PathGenerator/ProcessorMulti/barrier_detect.h \
    $$PWD/VisualMisc/CombinedVisual/VisualizationMulti/sensorwidgets.h

